name: laurentroger
favicon: null
layout_spectrum: 0.9031804034020752
typography_spectrum: 0.19876966997981071
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9090610253624618
  lightness: 0.3635200292337686
  saturation: 0.3377768746577203
  rhythmicContrast: 0.06706227012909949
purpose: []
